apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./yaml.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: nginx:MyCoolVersion
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: foo
        value: "bar"

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
      spec:
        template:
          spec:
            containers:
              - name: nginx
                env:
                  - name: foo
                    value: "bar"
